baseurl = "https://alexdamour.com/blog"
relativeURLs = true
enableEmoji = true
languageCode = "en-us"
title = "Alex D'Amour's Blog"
theme = "hugo-tanka"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About Me"
    url = "https://www.alexdamour.com"

[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/alexdamour"
    
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/alexdamour"
    
[social]
    github = "https://github.com/alexdamour"
    twitter = "https://twitter.com/alexdamour"

[params]
    sitename = "Alex D'Amour's Blog"
    description = "Statistics, Machine Learning, Causal Inference, Other"
    description2 = "Hot takes that are too long for twitter."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github-gist"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

